name: 'Release Drafter'

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]

jobs:
  update_release_draft:
    name: 'Update release draft'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Update Release Drafter'
        uses: release-drafter/release-drafter@v5
        with:
          config-name: '.github/release-drafter.yml'
